FROM golang:alpine as build

WORKDIR /app
COPY . .
RUN env GOOS=linux GOARCH=arm GOARM=5 go build -o k8s-ecr-login-renew .

FROM arm32v7/alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=build /app/k8s-ecr-login-renew .
CMD ["./k8s-ecr-login-renew"]
