apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "A service account name is required" .Values.names.serviceAcount }}
  namespace: {{ .Release.Namespace | default "default" }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
