{{- if .Values.awsCredentials.secretValues.accessKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "A secret name must be defined" .Values.awsCredentials.secretName }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{ required "Secret key for access key id must be defined" .Values.awsCredentials.secretKeys.accessKeyId }}: {{ required "Value for access key id must be defined" .Values.awsCredentials.secretValues.accessKeyId }}
  {{ required "Secret key for secret access key must be defined" .Values.awsCredentials.secretKeys.secretAccessKey }}: {{ required "Value for secret access key must be defined" .Values.awsCredentials.secretValues.secretAccessKey }}
{{- end}}
