apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "A service account name is required" .Values.names.serviceAcount }}
  namespace: {{ .Release.Namespace | default "default" }}
{{- if .Values.forHelm }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ required "A cluster role name is required" .Values.names.clusterRole }}
{{- if .Values.forHelm }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - list
  - apiGroups: [""]
    resources:
      - secrets
      - serviceaccounts
      - serviceaccounts/token
    verbs:
      - 'delete'
      - 'create'
      - 'patch'
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ required "A cluster role binding name is required" .Values.names.clusterRoleBinding }}
{{- if .Values.forHelm }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ required "A cluster role name is requred" .Values.names.clusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ required "A service account name is required" .Values.names.serviceAcount }}
    namespace: {{ .Release.Namespace | default "default" }}
---
{{- if .Values.awsAccessKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "A secret name must be defined" .Values.aws.secretName }}
  namespace: {{ .Release.Namespace | default "default" }}
{{- if .Values.forHelm }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
type: Opaque
stringData:
  {{ required "Secret key for access key id must be defined" .Values.aws.secretKeys.accessKeyId }}: {{ required "Value for access key id must be defined" .Values.awsAccessKeyId }}
  {{ required "Secret key for secret access key must be defined" .Values.aws.secretKeys.secretAccessKey }}: {{ required "Value for secret access key must be defined" .Values.awsSecretAccessKey }}
---
{{- end}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ required "Cron job name is required" .Values.names.cronJob }}
  namespace: {{ .Release.Namespace | default "default" }}
{{- if .Values.forHelm }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
spec:
  schedule: "* */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
{{- if .Values.forHelm }}
          labels:
            app.kubernetes.io/name: {{ .Chart.Name }}
            helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/version: {{ .Chart.AppVersion }}        
{{- end }}
        spec:
          serviceAccountName: {{ required "Service account name is required" .Values.names.serviceAcount }}
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          containers:
          - name: k8s-ecr-login-renew
            imagePullPolicy: IfNotPresent
            image: nabsul/k8s-ecr-login-renew:v{{ required "An app version is required" .Chart.AppVersion }}
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ required "AWS credentials secret name is required" .Values.aws.secretName }}
                  key: {{ required "AWS credentials secret key acceess key id is required" .Values.aws.secretKeys.accessKeyId }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ required "AWS credentials secret name is required" .Values.aws.secretName }}
                  key: {{ required "AWS credentials secret key secret acceess key is required" .Values.aws.secretKeys.secretAccessKey }}
            - name: AWS_REGION
              value: {{ required "AWS region must be specified" .Values.awsRegion }}
            - name: DOCKER_SECRET_NAME
              value: {{ required "Secret name for Docker credentials is required" .Values.dockerSecretName }}
            - name: TARGET_NAMESPACE
              value: {{ required "Target namespace is required" .Values.targetNamespace }}
{{- if .Values.registries }}
            - name: DOCKER_REGISTRIES
              value: {{ .Values.registries }}
{{- end }}
