apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
{{ include "k8s-ecr-login-renew.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
{{ include "k8s-ecr-login-renew.podLabels" . | indent 12 }}
    spec:
      serviceAccountName: {{ include "k8s-ecr-login-renew.serviceAccount" . }}
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
      - name: k8s-ecr-login-renew
        imagePullPolicy: IfNotPresent
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "k8s-ecr-login-renew.secret" . }}
                key: {{ .Values.ecr.auth.secretKeys.awsAccessKeyIdKey }}
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "k8s-ecr-login-renew.secret" . }}
                key: {{ .Values.ecr.auth.secretKeys.awsSecretAccessKeyKey }}
          - name: AWS_REGION
            value: {{ .Values.ecr.region }}
          - name: DOCKER_SECRET_NAME
            value: {{ .Values.secretName }}
          - name: TARGET_NAMESPACE
            value: {{ include "k8s-ecr-login-renew.targetNamespace" . }}
{{- if .Values.ecr.dockerRegistries }}
          - name: DOCKER_REGISTRIES
            value: {{ .Values.ecr.dockerRegistries }}
{{- end }}
