apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "A service account name is required" .Values.serviceAccountName }}
  namespace: {{ required "A target namespace is required" .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ required "A cluster role name is required" .Values.clusterRoleName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-7"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - list
  - apiGroups: [""]
    resources:
      - secrets
      - serviceaccounts
      - serviceaccounts/token
    verbs:
      - 'delete'
      - 'create'
      - 'patch'
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ required "A cluster role binding name is required" .Values.clusterRoleBindingName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ required "A cluster role name is requred" .Values.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ required "A service account name is required" .Values.serviceAccountName }}
    namespace: {{ required "A target namespace is required" .Release.Namespace }}
